.PHONY: clean All

All:
	@echo "----------Building project:[ PECL - Debug ]----------"
	@cd "PECL" && "$(MAKE)" -f  "PECL.mk"
clean:
	@echo "----------Cleaning project:[ PECL - Debug ]----------"
	@cd "PECL" && "$(MAKE)" -f  "PECL.mk" clean
